# Generated by Django 6.0.4 on 2026-04-10 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genz_fashion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='images',
            field=models.ImageField(upload_to='static/image'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='static/img')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genz_fashion.category')),
            ],
        ),
    ]
