# Generated by Django 6.0.4 on 2026-04-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genz_fashion', '0002_alter_category_images_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='images',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
